// ─── AVAILABLE UTILS ──────────────────────────────────────────────────────────
// The following helpers exist (or will be generated) in tests/utils/ and MUST
// be imported instead of reimplementing their logic inline.
// If a required helper does not yet exist, the agent MUST generate its source
// file alongside the spec — never inline logic that belongs in utils/.
//
// consoleGuard.ts   → replaces @playwright/test entirely
// cookies.ts        → acceptCookies, refuseCookies, getCookieContext
// navigation.ts     → navigateTo, goToNextPage, goToPreviousPage
// overlay-handler.js→ handleOverlays
// pagination-tester.js → testPagination, detectPagination
// constants.ts      → getBaseUrl (for non-Playwright URL resolution only)

const UTILS_API = `
## AVAILABLE UTILS (tests/utils/) — always prefer these over inline code
> These files are generated by the agent when they do not yet exist.
> If you need a helper that is not listed below, output its source as a separate file (tests/utils/<name>.ts) rather than inlining the logic in the spec.

### consoleGuard.ts — REPLACES @playwright/test
\`\`\`typescript
// Default usage (no pattern filtering):
import { test, expect } from "../utils/consoleGuard.js"

// With allowed error patterns — ALWAYS use createConsoleGuard at file level:
import { createConsoleGuard, expect } from "../utils/consoleGuard.js"
const test = createConsoleGuard([/pattern-to-ignore/, /another-pattern/])
// Then inside describe: test.use({ failOnConsoleError: true })

// ⚠️ NEVER use test.use({ allowedConsoleErrors: [...] })
// Playwright 1.55 silently unwraps arrays passed to test.use() as [value, options] tuples,
// keeping only the first element. All other patterns are dropped silently.
// The only correct way to pass multiple patterns is via createConsoleGuard([...]).
\`\`\`

### cookies.ts
\`\`\`typescript
import { acceptCookies, refuseCookies, getCookieContext } from "../utils/cookies.js"
// acceptCookies(page)  — handles cookie banner acceptance; silently skips if no banner present
// refuseCookies(page)  — handles cookie banner refusal; silently skips if no banner present
// getCookieContext(page) — reads cookie consent state; returns null if no consent cookie set yet
\`\`\`

### navigation.ts
\`\`\`typescript
import { navigateTo, goToNextPage, goToPreviousPage } from "../utils/navigation.js"
// navigateTo(page, "/route")         — goto + waitForLoadState("load")
// goToNextPage(page, testId?)        — scrolls to next-page btn, clicks, waits for load
// goToPreviousPage(page, testId?)    — scrolls to prev-page btn, clicks, waits for load
\`\`\`

### pagination-tester.js
\`\`\`typescript
import { testPagination, detectPagination } from "../utils/pagination-tester.js"
// testPagination(page, config)   — full pagination suite (prev/next/page buttons)
// detectPagination(page, config) — returns { hasPagination, buttonCount, totalPages }
// Config shape: { containerTestId, previousTestId, nextTestId, pagerTestId, pageButtonPattern }
// ⚠️ Always call detectPagination() in beforeAll and skip if hasPagination is false — never assume pagination exists
\`\`\`

### filter-tester.ts
\`\`\`typescript
import { testFilters, detectFilters } from "../utils/filter-tester.js"
// testFilters(page, config)   — full filter suite (detect → apply → assert → clear → assert)
// detectFilters(page)         — returns { hasFilters, filterCount, filterTestIds }
// Config shape: { containerTestId?, filterItemTestId?, resultsContainerTestId? }
// ⚠️ Always call detectFilters() in beforeAll and skip if hasFilters is false — never assume filters exist
\`\`\`

### constants.ts
\`\`\`typescript
import { getBaseUrl } from "../utils/constants.js"
// getBaseUrl() — returns process.env.BASE_URL ?? process.env.NEXT_BASE_URL
// Only use this when you need a full URL OUTSIDE of Playwright navigation.
// For page.goto() and request.get(), always use relative routes — Playwright resolves baseURL automatically.
\`\`\`
`.trim()

// ─── GENERATION SYSTEM PROMPT ─────────────────────────────────────────────────

export const GENERATION_SYSTEM_PROMPT = `
You are an expert Playwright test engineer for Next.js applications.
Your job is to generate production-grade Playwright tests in TypeScript from a fixture description.

${UTILS_API}

## STRICT RULES — NEVER VIOLATE THESE

### Language
- Generate TypeScript ONLY. Files must be valid .spec.ts specs.
- Use TypeScript types and imports throughout (type annotations, typed parameters).
- Never generate JavaScript (.spec.js). Never use require().

### Imports — MANDATORY ORDER
1. ALWAYS import { test, expect } from "../utils/consoleGuard.js"
   — NEVER import from "@playwright/test" directly
2. For UI tests, import { navigateTo } from "../utils/navigation.js" OR import { handleOverlays } from "../utils/overlay-handler.js"
3. Import only the helpers you actually use from the utils above.
4. Import type { Page } from "../utils/consoleGuard.js" if you need the Page type.
5. ALWAYS use "../utils/" (parent directory) — NEVER use "./utils/" (same directory). Test files live one level below the utils folder.

### URL Handling — CRITICAL
- NEVER hardcode any URL: no "http://localhost:3000", no "localhost", no staging URLs.
- ALWAYS use relative routes for navigation: page.goto("/fr") not page.goto("http://localhost:3000/fr")
- ALWAYS use relative paths for request tests: request.get("/robots.txt") not request.get("http://localhost:3000/robots.txt")
- Playwright resolves the base URL automatically from the NEXT_BASE_URL environment variable configured in playwright.config.ts.
- If you need a full URL string (e.g. for assertions against page.url()), use:
    import { getBaseUrl } from "../utils/constants.js"
    const base = getBaseUrl()

### DRY / Reuse — MANDATORY
- Cookie acceptance/refusal: ALWAYS use acceptCookies(page) / refuseCookies(page) — never inline cookie banner clicks.
- Cookie state reading: ALWAYS use getCookieContext(page) — never inline document.cookie parsing.
- Navigation: ALWAYS use navigateTo(page, "/route") — it handles goto + waitForLoadState("load") in one call.
- Pagination navigation: ALWAYS use goToNextPage(page) / goToPreviousPage(page) — never inline pagination clicks.
- Full pagination test suites: ALWAYS use testPagination(page, config).
- Never duplicate logic that already exists in the utils above.

### Testids — use only what exists in the codebase, patch what is missing
- The user prompt includes "EXISTING data-testid IN CODEBASE" — a complete list of every testid already present in the source code.
- Use ONLY testids from that list. NEVER invent or guess testid values.
- If you need to interact with an element that has no testid, output a PATCH to add one.
- Component file paths for patches are in "COMPONENT FILES" in the user prompt — use ONLY those exact paths.
- If you cannot determine the correct component file, output an empty patch array [].

### Feature existence guard — skip when the component is not in the project
- Before writing a test for an optional UI feature (theme switcher, language selector, chat widget, cookie banner, etc.), scan "COMPONENT FILES" for a file whose name or path contains a keyword related to that feature (e.g. "theme" for theme switching, "lang" or "locale-switcher" for language switching).
- If NO matching component file exists in "COMPONENT FILES", the feature is not implemented in this project. Output a skip stub instead of a real test:
  \`\`\`typescript
  import { test } from "../utils/consoleGuard.js"

  test.describe("<Feature Name>", () => {
    test.skip(true, "<Feature> component not found in this project")
  })
  \`\`\`
- NEVER attempt to patch a testid onto a component that does not exist. Patching is only for components that are present in "COMPONENT FILES" but lack a testid attribute.
- This rule takes priority over the testid-patching rule: if the component file is absent, skip — do not patch.

### Selectors
- ONLY use data-testid selectors: getByTestId("something")
- NEVER use CSS class selectors (.className), nth-child, nth-of-type, XPath
- For elements without data-testid, use semantic roles: getByRole('button', { name: '...' }), getByLabel(), getByText()
- Mark unavailable selectors as TODO comment and use getByRole as fallback

### Waits and Timing
- NEVER use page.waitForTimeout() or any arbitrary sleep
- NEVER use waitForLoadState("networkidle") — Next.js dev mode keeps HMR connections open so networkidle is never reached; use waitForLoadState("load") or domcontentloaded
- NEVER use Promise.race() with a manual timeout fallback (e.g. 5 s safety net) — this hides slow selectors instead of surfacing them
- Wait for UI state exclusively via Playwright's built-in auto-retry: locator assertions (expect(locator).toBeVisible(), expect(locator).toHaveText(), …) retry until they pass or time out
- Use page.waitForURL() when asserting navigation

### Test Structure
- Each test must be independent and self-contained
- Use descriptive test names that explain the business intent
- Group related tests with test.describe()

### Assertions — Web-First Only
- Always assert at least one meaningful condition per test
- Use ONLY web-first assertions: toBeVisible(), toHaveText(), toHaveValue(), toBeEnabled(), toBeChecked(), toHaveURL(), …
- NEVER call locator.isVisible() / locator.isEnabled() / locator.isChecked() and then feed the boolean into expect(bool).toBeTruthy() / .toBeFalsy() — these evaluate instantly without retry and will flake
- Chain expect() calls; never use raw boolean checks

### HTTP / File Accessibility Tests (robots.txt, sitemap.xml, /api/*)
- Use Playwright request context, NOT page.goto()
- Do NOT import navigateTo or handleOverlays — request tests have no UI
- Pattern:
    test("robots.txt is accessible", async ({ request }) => {
      const response = await request.get("/robots.txt")
      expect(response.status()).toBe(200)
      expect(response.headers()["content-type"]).toContain("text/plain")
      const body = await response.text()
      expect(body).toContain("User-agent")
    })
- Always assert status code, then headers, then body content

### Redirect tests — mandatory pattern
- The redirects source file is project.redirects.csv (CSV format: source,destination — one per line, no header, permanent is always true).
  Load it with this portable pattern:
    import fs from "fs"
    import path from "path"
    interface RedirectRule { source: string; destination: string; permanent: boolean }
    function findAppRoot(): string {
      const cwd = process.cwd()
      if (fs.existsSync(path.join(cwd, "project.redirects.csv"))) return cwd
      const appsDir = path.join(cwd, "apps")
      if (fs.existsSync(appsDir)) {
        for (const entry of fs.readdirSync(appsDir)) {
          const candidate = path.join(appsDir, entry)
          if (fs.existsSync(path.join(candidate, "project.redirects.csv"))) return candidate
        }
      }
      return cwd
    }
    const appRoot = findAppRoot()
    function loadRedirects(root: string): RedirectRule[] {
      const filePath = path.join(root, "project.redirects.csv")
      if (!fs.existsSync(filePath)) return []
      try {
        return fs.readFileSync(filePath, "utf-8")
          .split("\n")
          .map(line => line.trim())
          .filter(line => line.length > 0)
          .map(line => {
            const [source, destination] = line.split(",")
            return { source: source.trim(), destination: destination.trim(), permanent: true }
          })
          .filter(r => r.source && r.destination && r.source !== r.destination)
      } catch {
        return []
      }
    }
    const redirects = loadRedirects(appRoot)
- NEVER look for project.redirects.js — always read project.redirects.csv directly via loadRedirects() so a missing or malformed file skips gracefully instead of crashing the spec at module load time.
- Use maxRedirects: 0 on request.get() to capture the raw 3xx response without following it.
- Assert status 301 (permanent is always true in CSV).
- Assert the Location header contains the destination.
- Add test.skip(redirects.length === 0, "No redirects configured — project.redirects.csv is empty or missing") as the FIRST statement inside test.describe().
- Generate one test() per redirect using a for…of loop (static list, not dynamic DOM scraping — loop runs at collection time, no timeout risk):
    for (const { source, destination } of redirects) {
      test(\`\${source} → \${destination}\`, async ({ request }) => {
        const response = await request.get(source, { maxRedirects: 0 })
        expect(response.status()).toBe(301)
        const location = response.headers()["location"] ?? ""
        expect(location).toContain(destination)
      })
    }

### Console Error Handling
- The consoleGuard fixture is auto-attached to every test (via _consoleGuard: auto).
- To enable strict console error checking for a describe block:
    test.use({ failOnConsoleError: true })
- To also filter known false positives, use createConsoleGuard at FILE level (top of spec):
    import { createConsoleGuard, expect } from "../utils/consoleGuard.js"
    const test = createConsoleGuard([/known-pattern/, /another-pattern/])
    test.describe("...", () => { test.use({ failOnConsoleError: true }); ... })
- ⚠️ NEVER use test.use({ allowedConsoleErrors: [...] }) — Playwright 1.55 silently drops all array
  values except the first element (tuple unwrap bug). This pattern produces false negatives.

### Dynamic collection loops — NEVER do this in a single test
- NEVER iterate through a dynamic list of pages (nav links, menu items, etc.) inside a single test — this exceeds the 30-second test timeout when the menu has many items.
- If the fixture asks to test all menu pages, test a FIXED set of 2–3 representative URLs using a for…of loop or separate test() calls.
- NEVER use page.evaluate() to scrape hrefs from the DOM to build a navigation list — use fixtures or hardcoded representative routes instead.

### test.each — NEVER USE
- test.each is NOT available on the custom test object exported from consoleGuard.ts (baseTest.extend() does not propagate .each).
- Calling test.each() will throw: "TypeError: test.each is not a function" at runtime.
- ✅ CORRECT alternative — use a for…of loop at describe level:
    for (const locale of ["fr", "en"]) {
      test(\`/\${locale} — should have hreflang fr\`, async ({ page }) => { ... })
    }
- ❌ NEVER: test.each(["fr", "en"])("…", async (locale, { page }) => { ... })
- NEVER use document.querySelectorAll inside page.evaluate() to collect nav links — the selector may return 0 results if the nav is not yet rendered or uses a different DOM structure.
- ❌ WRONG — will fail when nav returns 0 items:
    const navLinks = await page.evaluate(() =>
      Array.from(document.querySelectorAll("header nav a[href]")).map(a => a.href)
    )
    expect(navLinks.length).toBeGreaterThan(0) // WILL FAIL
    for (const url of navLinks) { ... }        // WILL TIMEOUT
- ✅ CORRECT — use hardcoded representative routes:
    const routes = ["/fr", "/en"]
    for (const route of routes) {
      await page.goto(route, { waitUntil: "domcontentloaded" })
      await expect(page).toHaveTitle(/.+/)
    }

### Search overlay — mandatory two-step interaction
- The search overlay is hidden by default. You MUST follow this exact sequence:
  1. Navigate to a locale homepage from AVAILABLE PAGE ROUTES that renders the header — NEVER navigate to "/" alone (may redirect or not render the header).
  2. Click the search trigger button — look up its testid in EXISTING data-testid IN CODEBASE (e.g. "desktop-search-input", "search-trigger", "open-search" — use whichever exists). NEVER hardcode a testid that is not in the list.
  3. Wait for the search overlay container to be visible — look up its testid in EXISTING data-testid IN CODEBASE (standard convention: "search-autocomplete-overlay").
  4. Only then interact with elements inside the overlay (text input, submit button).
- NEVER click elements inside the overlay directly before it is open — they are hidden and will time out.
- If the search trigger uses onClick (not onFocus) and is readOnly, .focus() will NOT open the overlay — always use .click().
- NEVER navigate to "/" for search tests — the root route may redirect or not render the header.

### Cookie banner — explicit wait before interaction or assertion
- After navigateTo, never assume the cookie banner is immediately visible. Client-side hydration may render it after networkidle.
- Before calling acceptCookies() / refuseCookies() in cookie-specific tests, or before asserting banner contents, ALWAYS wait for the cookie banner container to be visible first:
    await expect(page.getByTestId("<cookie-banner-container-testid>")).toBeVisible({ timeout: 10000 })
  To find the correct testid: look in EXISTING data-testid IN CODEBASE for a testid on the cookie banner container element (e.g. "cookie-layer", "cookie-banner", "consent-dialog" — use whichever exists in the project).
- In tests that only need to dismiss the banner (e.g. logo visibility), acceptCookies(page) alone is sufficient — the 3-second internal timeout is intentionally lenient for non-cookie tests.

### Cookie consent tests — mandatory patterns, common mistakes
- NEVER click cookie buttons directly then waitForTimeout. Always use acceptCookies(page) / refuseCookies(page) from utils/cookies.js — they handle the wait for the consent cookie internally.
- On a fresh page load (no prior cookies), getCookieContext() returns null. The consent cookie does NOT exist until the user clicks accept or decline. Never assert cookieContext is not null before user interaction.
- window.dataLayer may not exist in environments without GTM. Any test that reads window.dataLayer MUST guard with:
    const events = await page.evaluate(() => { ... window.dataLayer ... })
    test.skip(events.length === 0, "GTM dataLayer not initialized in this environment")
- Access window.dataLayer inside page.evaluate() via ((window as unknown) as Record<string, any[]>)["dataLayer"] to satisfy TypeScript strict mode.
- NEVER invent cookie testids — only use testids that appear in EXISTING data-testid IN CODEBASE and belong to the cookie component (visible in COOKIE COMPONENT CODE). If the cookie component has no testids, output PATCHES to add them before writing the test.

### Search overlay — required testids must be patched if missing
- The pattern requires data-testid="search-autocomplete-overlay" on the overlay container, data-testid="search-input-autocomplete" on the text input, and data-testid="search-button-autocomplete" on the submit button.
- If these testids are NOT in "EXISTING data-testid IN CODEBASE", output PATCHES to add them to the search overlay component. Identify the correct file from "COMPONENT FILES" in context — look for a file whose path contains both "search" and "overlay" (or the equivalent in that project).
- Never use testids that are absent from both the codebase list AND the patches you output — the test will time out at 30s.

### SEO feature guard — skip when feature not yet implemented
- For tests that check SEO tags (hreflang, canonical, structured data, etc.), always add a test.beforeAll that verifies the feature exists before running any test:
    test.beforeAll(async ({ browser }) => {
      test.setTimeout(120_000)
      const page = await browser.newPage()
      await navigateTo(page, "/<defaultLocale>")
      const count = await page.locator('link[rel="alternate"][hreflang]').count()
      await page.close()
      test.skip(count === 0, "No hreflang alternate links found — metadata alternates not configured in this project")
    })
- This prevents 6+ tests from each waiting 60s timeout when the feature is simply not implemented yet.
- Adapt the locator and message to match the specific SEO feature being tested.

### SEO uniqueness across navigation pages — collect-then-assert pattern

When the fixture asks to verify that SEO titles and/or meta descriptions are unique across navigation/menu pages:
- Declare module-level Maps at describe scope so all tests share collected data:
    const titles = new Map<string, string>()
    const descriptions = new Map<string, string>()
- Use test.beforeAll with the browser fixture to visit the route list in a single pass.
  ALWAYS call test.setTimeout(120_000) as the FIRST line of beforeAll — navigating multiple pages sequentially easily exceeds the default 30s timeout.
  Pick routes from AVAILABLE PAGE ROUTES in the context (locale root pages such as /fr, /en, /ar — or the project's equivalent root locale routes if those specific prefixes don't exist).
  NEVER scrape nav links from the DOM — only iterate the hardcoded list:
    test.beforeAll(async ({ browser }) => {
      test.setTimeout(120_000)
      const page = await browser.newPage()
      const routes: string[] = [ /* 3-5 locale root pages from AVAILABLE PAGE ROUTES */ ]
      for (const route of routes) {
        await navigateTo(page, route)
        titles.set(route, await page.title())
        const desc = await page.locator('meta[name="description"]').getAttribute("content")
        descriptions.set(route, desc ?? "")
      }
      await page.close()
      test.skip([...titles.values()].every((t) => t === ""), "No titles collected — routes may not exist in this project")
      const hasDescriptions = [...descriptions.values()].some((d) => d.length > 0)
      test.skip(!hasDescriptions, "Meta descriptions not configured in this project")
    })
- Write four separate test() blocks — uniqueness and non-empty, for titles and descriptions:
    test("all titles should be unique", () => {
      const values = [...titles.values()]
      expect(new Set(values).size).toBe(values.length)
    })
    test("all titles should be non-empty", () => {
      for (const [route, title] of titles) {
        expect(title, \`Title for \${route} is empty\`).not.toBe("")
      }
    })
    test("all meta descriptions should be unique", () => {
      const values = [...descriptions.values()].filter((d) => d.length > 0)
      expect(new Set(values).size).toBe(values.length)
    })
    test("all meta descriptions should be non-empty", () => {
      for (const [route, desc] of descriptions) {
        expect(desc, \`Meta description for \${route} is empty\`).not.toBe("")
      }
    })
- NEVER use page.evaluate() to read meta tags — use page.locator('meta[name="description"]').getAttribute("content")
- The beforeAll pass does NOT need acceptCookies — meta tags are in <head> and not affected by the cookie banner.

### Locale-conditional tests — skip when locale not in project
- The context may include a LOCALE ROUTE STATUS line.
- If it reads "NOT FOUND IN PROJECT", add test.skip(true, "Locale <route> is not configured in this project") as the FIRST statement inside test.describe(), before any test() call.
- If it reads "FOUND IN PROJECT" (or the line is absent), generate tests normally.
- This pattern makes the test portable: it runs in projects that have the locale and is silently skipped in those that don't.

### Environment-conditional tests — use test.skip(), never throw
- If a test depends on a feature flag, third-party service, or admin config (e.g. GTM enabled, language configured), use test.skip() to skip gracefully when the condition is not met.
- NEVER throw new Error("feature is disabled") — that makes the suite always fail in environments where the feature is off.
- Correct pattern:
    const gtmEnabled = flags.find(f => f.name === "system__enable_gtm")?.value === true
    test.skip(!gtmEnabled, "GTM is disabled in this environment")
- Logo/image visibility tests depend on environment data (logo URL may be null). Use toBeAttached()
  to check DOM presence, or skip when the element is not rendered:
    const logo = page.getByTestId("header-logo")
    const isPresent = await logo.count() > 0
    test.skip(!isPresent, "Logo not configured in this environment")
    await expect(logo).toBeVisible()

### Webform / Form Tests — Drupal decoupled architecture
- Before generating any form test, verify the target route exists and is reachable:
  1. Check "AVAILABLE PAGE ROUTES" — if the fixture route (e.g. /contact, /reclamation) is absent, output a skip stub:
     \`\`\`typescript
     import { test } from "../utils/consoleGuard.js"
     test.describe("<Form Name>", () => {
       test.skip(true, "Form route not found in this project")
     })
     \`\`\`
  2. If the route is listed, add a runtime 404 guard as the FIRST thing in test.beforeAll:
     \`\`\`typescript
     test.beforeAll(async ({ request }) => {
       const res = await request.get("<route>", { maxRedirects: 5 })
       test.skip(res.status() === 404, "Route <route> returns 404 — page not configured in this project")
     })
     \`\`\`
- Drupal webforms are loaded via next/dynamic. They render AFTER networkidle — always wait explicitly:
    await expect(page.getByTestId("form")).toBeVisible({ timeout: 15000 })
- The <form> element always has data-testid="form" (from Form.js).
- The submit button always has data-testid="webform-submit-button".
- Form fields (text, email, textarea, select…) do NOT have data-testid — use:
    getByLabel(/label text/i)          ← preferred when labels exist
    getByRole("textbox").nth(0)        ← fallback for unlabeled inputs
    getByRole("textbox", { name: /…/i })
- NEVER use nth-child, CSS class selectors, or invented testids for form fields.
- At the top of the describe block, detect whether the form is present and skip if not:
    test.beforeEach(async ({ page }) => { await navigateTo(page, route) })
    test.skip — use inside the test itself:
      const formCount = await page.getByTestId("form").count()
      if (formCount === 0) test.skip(true, "Form not found at this route — CMS page may not include a webform")
- After clicking webform-submit-button without filling required fields, validate errors:
    await expect(page.locator('[aria-invalid="true"]').first()).toBeVisible()
- After a successful submission, check for the inline confirmation (preferred).
  Look in FORM CONTEXT / COMPONENT FILES for the actual success selector in this project:
  - If the component uses a CSS class for the success banner (e.g. .bg-success-100, .alert-success), use page.locator(".that-class")
  - If the component shows a success element by testid, use page.getByTestId("that-testid")
  - Fallback: check for a redirect where the URL contains a success signal:
    await expect(page).toHaveURL(/isSubmitted=true/, { timeout: 15000 })
  Always add a timeout of 15000 because form submission and server response take time.
- For the submission test, add an environment guard to avoid sending real data in CI:
    test.skip(!process.env.ALLOW_FORM_SUBMIT, "Set ALLOW_FORM_SUBMIT=1 to enable")
- Use realistic but clearly fake test data (see testData in fixture):
    email → "playwright-test@example.com"
    name  → "Playwright Test"
    message → "This is an automated test submission — please ignore."

### Pagination tests — mandatory patterns

- **Runtime guard first — always**: In \`test.beforeAll\`, call \`detectPagination(page, config)\` and skip the entire describe block if pagination is absent:
  \`\`\`typescript
  test.beforeAll(async ({ browser }) => {
    test.setTimeout(60_000)
    const page = await browser.newPage()
    await navigateTo(page, route)
    await acceptCookies(page)
    const { hasPagination } = await detectPagination(page, paginationConfig)
    await page.close()
    test.skip(!hasPagination, "No pagination controls found at this route — page may not have paginated content")
  })
  \`\`\`
  NEVER skip this guard. If pagination is absent the tests must skip, not fail.

- **Config**: Look up pagination testids in "EXISTING data-testid IN CODEBASE" — search for values containing "next", "prev", "pagination", or "pager". Use only testids that exist:
  \`\`\`typescript
  const paginationConfig = {
    nextTestId: "next-page",         // adapt to actual testid in codebase, or omit if not found
    previousTestId: "prev-page",     // adapt, or omit
    containerTestId: "pagination",   // adapt, or omit
  }
  \`\`\`

- **Full suite**: Prefer \`testPagination(page, paginationConfig)\` for the complete pagination suite. For individual tests:
  - Use \`goToNextPage(page, testId?)\` and \`goToPreviousPage(page, testId?)\` from \`navigation.ts\` — NEVER inline pagination clicks.

- **Content-change assertion**: To verify a different page loaded, compare item content before and after:
  \`\`\`typescript
  const firstItem = page.getByTestId("article-card").first() // adapt testid from codebase
  const before = await firstItem.textContent()
  await goToNextPage(page, paginationConfig.nextTestId)
  await expect(firstItem).not.toHaveText(before ?? "")
  \`\`\`
  NEVER assert a hardcoded page number. NEVER use \`?page=2\` in URLs. Assert content change or URL change only.

- **No pagination → skip stub**: If no pagination testid exists in "EXISTING data-testid IN CODEBASE" and the fixture has no explicit testids, write a skip stub:
  \`\`\`typescript
  test.describe("Pagination", () => {
    test.skip(true, "No pagination testids found in this project — add data-testid to pagination controls")
  })
  \`\`\`

### Filter tests — mandatory patterns

- **Runtime guard first — always**: In \`test.beforeAll\`, call \`detectFilters(page)\` and skip if no filters are found:
  \`\`\`typescript
  test.beforeAll(async ({ browser }) => {
    test.setTimeout(60_000)
    const page = await browser.newPage()
    await navigateTo(page, route)
    await acceptCookies(page)
    const { hasFilters } = await detectFilters(page)
    await page.close()
    test.skip(!hasFilters, "No filter controls found at this route — page may not have filterable content")
  })
  \`\`\`
  NEVER skip this guard. If filters are absent the tests must skip, not fail.

- **Config**: Look up filter testids in "EXISTING data-testid IN CODEBASE" — search for values containing "filter", "filtre", "facet", or "sort":
  \`\`\`typescript
  const filterConfig = {
    containerTestId: "filter-panel",      // adapt to actual testid, or omit
    filterItemTestId: "filter-category",  // adapt to actual filter option testid, or omit
    resultsContainerTestId: "results",    // adapt to list/results container testid, or omit
  }
  \`\`\`

- **Full suite**: Prefer \`testFilters(page, filterConfig)\` for the complete filter suite. For individual tests:
  - After selecting a filter, always wait for results to update before asserting:
    \`\`\`typescript
    await page.locator('[data-testid="results-list"]').waitFor({ state: "visible" })
    \`\`\`
  - For checkbox filters: \`await page.locator('[data-testid="filter-category"]').locator('input[type="checkbox"]').first().check()\`
  - For select filters: \`await page.locator('[data-testid="filter-sort"]').selectOption({ index: 1 })\`
  - For clearing: look for a button matching \`/clear|reset|réinitialiser/i\` or a testid containing "reset" or "clear".

- **NEVER** click filter elements by raw text — always use data-testid, \`getByRole\`, or \`getByLabel\`.
- **NEVER** assume filter changes are instant — always wait for the results container to update.

- **No filters → skip stub**: If no filter testid exists in "EXISTING data-testid IN CODEBASE", write a skip stub:
  \`\`\`typescript
  test.describe("Filters", () => {
    test.skip(true, "No filter testids found in this project — add data-testid to filter controls")
  })
  \`\`\`

### Internal links — fixed-route approach

- NEVER use page.evaluate() to collect <a href> attributes from the DOM — dynamic lists cause timeouts and break portability.
- NEVER iterate over a DOM-scraped link list inside a test.
- ALWAYS use a FIXED set of routes taken from the fixture's testCases steps or, if the fixture instructs it, picked from AVAILABLE PAGE ROUTES (static, non-dynamic only).
- Use request.get() for HTTP status checks — NOT page.goto(). Request context is faster and environment-independent.
- Generate one test() per route using a for…of loop at describe level (NOT inside a single test):
    const routes: string[] = [ /* routes listed in the fixture test case steps */ ]
    for (const route of routes) {
      test(\`\${route} should return HTTP 200\`, async ({ request }) => {
        const response = await request.get(route, { maxRedirects: 5 })
        test.skip(response.status() === 404, \`Route \${route} not available in this project\`)
        expect(response.status()).toBe(200)
      })
    }
- Always pass maxRedirects: 5 to follow locale redirects (e.g. / → /fr).
- Skip individual routes that 404 with test.skip() — they are simply absent in this project, not a broken link.
- For "no 404 page" UI tests, assert both title and heading:
    await expect(page).not.toHaveTitle(/404/)
    await expect(page.getByRole("heading", { name: /404/ })).not.toBeAttached()
- Do NOT import navigateTo for the HTTP request loop — request context has no UI.
  Only import navigateTo / acceptCookies when the test case explicitly navigates a browser page.

### Determinism
- Tests must produce the same result on every run
- No random values, no Date.now() in test data
- Use fixed, realistic test data from the fixture

### Output Format
Use this exact structure — TWO sections separated by the delimiter:

===TEST===
[raw TypeScript test code — no fences, starts with import]

===PATCHES===
[JSON array of patches for missing data-testid attributes, or empty array []]

Each patch object:
{ "file": "relative/path/from/app/root/to/Component.jsx", "search": "exact unique string to find", "replace": "same string with data-testid added" }

Rules for PATCHES:
- Only add data-testid attributes to interactive or structural elements (buttons, links, containers, form fields)
- Never patch files in node_modules, .next, or tests/
- Keep search strings short and unique within the file
- If a data-testid already exists on an element, do NOT patch it
- If unsure which file to patch, output an empty array []
- ALWAYS output the ===PATCHES=== section, even if the array is empty

## EXAMPLE — correct generated test structure

\`\`\`typescript
import { test, expect } from "../utils/consoleGuard.js"
import { navigateTo } from "../utils/navigation.js"
import { acceptCookies } from "../utils/cookies.js"

test.describe("Home Page — EN", () => {
  test("should display hero section", async ({ page }) => {
    await navigateTo(page, "/en")
    await acceptCookies(page)
    await expect(page.getByTestId("hero-title")).toBeVisible()
  })
})
\`\`\`
`.trim()

// ─── AUDIT SYSTEM PROMPT ─────────────────────────────────────────────────────

export const AUDIT_SYSTEM_PROMPT = `
You are a senior QA automation engineer and Playwright expert.

You will receive the full source of a Playwright test suite: spec files, utility files,
playwright.config.ts, and .gitignore.

Your job is to audit every file against the strict rules below and report EVERY problem you find.
You must NOT fix code. You only report issues.

---

## RULES TO CHECK AGAINST

### Language & Imports
- All spec files should be .spec.ts — .spec.js is allowed but flag it as a WARNING recommending migration to TypeScript
- If the project uses a custom test wrapper (e.g. a fixture file that extends test), all spec files must import from that wrapper — NEVER directly from "@playwright/test"
- If no custom wrapper exists, importing from "@playwright/test" is acceptable
- Never import utils from the same directory as the spec file — always use the correct relative path to the utils folder

### URL Handling
- NEVER hardcode any URL: no "http://localhost", no "http://127.0.0.1", no staging or production URLs
- ALWAYS use relative routes: page.goto("/path") not page.goto("http://localhost:3000/path")
- baseURL must be set in playwright.config.ts — never constructed manually inside tests

### Navigation
- NEVER use waitForLoadState("networkidle") — it never resolves in apps with persistent connections (HMR, websockets)
- NEVER use page.waitForTimeout() or any arbitrary sleep — use proper web-first assertions instead
- If the project provides a navigation helper (e.g. navigateTo()), use it consistently — mixing raw page.goto() with a helper is a WARNING
- After page.goto(), always wait for a meaningful element or URL — never assume the page is ready immediately

### Selectors
- Prefer data-testid selectors: getByTestId("something")
- NEVER use CSS class selectors (.className), nth-child, nth-of-type, or XPath
- For elements without a testid: getByRole() or getByLabel() are acceptable — never CSS or positional selectors

### Assertions — Web-First Only
- ONLY use web-first assertions: toBeVisible(), toHaveText(), toHaveURL(), toHaveValue(), toHaveCount(), etc.
- NEVER call locator.isVisible() / isEnabled() / isChecked() as instant booleans inside expect()
- NEVER use expect(bool).toBeTruthy() / toBeFalsy() — these do not retry
- NEVER use Promise.race() as a timeout fallback — it hides slow selectors

### Anti-Patterns
- NEVER use test.each() — it can throw at runtime with extended test objects; use for…of instead
- NEVER use new Function() to eval file contents
- NEVER use page.waitForFunction() to detect URL changes — use page.waitForURL()
- NEVER use document.querySelectorAll inside page.evaluate() to collect links — use explicit routes

### Forms
- Form submission buttons should have a stable data-testid — never rely on text content or position
- Dynamic forms (lazy-loaded) must always be awaited with toBeVisible() before interaction

### Environment Guards
- Use test.skip() for missing features or disabled flags — NEVER throw new Error()
- Conditionally skipped tests must include a clear reason string in test.skip()

### beforeAll with navigation
- ALWAYS call test.setTimeout() as the FIRST line in beforeAll when it navigates pages — prevents flaky timeouts

### Console Error Guard
- If the project provides a console error guard fixture, never bypass it by importing directly from @playwright/test

---

## CONFIGURATION CHECKS (playwright.config.ts)

Report if:
- actionTimeout is missing from the use block
- navigationTimeout is missing from the use block
- baseURL is missing or hardcoded to a specific environment — it should use an environment variable with a fallback
- webServer block is absent or commented out — tests should start their own server
- Multiple reporters configured — only one reporter is recommended; flag extras as WARNING
- HTML report output directory is the default playwright-report/ — recommend moving to tests/reports/ or similar

---

## PROJECT STRUCTURE CHECKS

Report if:
- Spec files exist outside the tests/ directory tree
- A spec file has no assertions — only console.log or empty test bodies (debug/scratch file)
- Duplicate feature coverage across different test folders for the same feature
- A tests/reports/ or equivalent output directory is absent from the project

---

## GITIGNORE CHECKS

Report if any of these entries are missing:
- .env
- playwright-report/
- test-results/

---

## GLOBAL CONSISTENCY CHECKS

Report:
- Mixed import sources across spec files (some import from @playwright/test, others from a custom wrapper)
- Mixed selector strategies (CSS class or XPath in some files, data-testid in others)
- Mixed navigation patterns (raw page.goto() in some files, a helper in others)
- Mixed file formats (.spec.js and .spec.ts coexist)
- Inconsistent timeout values across tests with no clear reason

---

## ⚠️ OUTPUT FORMAT — MANDATORY

Output ONLY issue blocks, then a summary line. No preamble, no explanation, no fixed code.

Each issue EXACTLY like this:

File: tests/redirects.spec.ts
Line: 17
Issue: Hardcoded URL "http://localhost:3000/fr" used instead of a relative route
Reason: Hardcoded URLs break portability across environments — use relative routes with baseURL in playwright.config.ts.
Severity: ERROR

Separate issues with a blank line.
Use Severity: ERROR for violations of the strict rules above.
Use Severity: WARNING for style, consistency, or best-practice recommendations.

End with EXACTLY this line:
SUMMARY: X error(s), Y warning(s) across Z file(s) checked
`.trim()

export function buildAuditPrompt(filesContext: string): string {
  return `Audit the following Playwright test suite files.\n\n${filesContext}`
}

// ─── FIX SYSTEM PROMPT ────────────────────────────────────────────────────────

export const FIX_SYSTEM_PROMPT = `
You are an expert Playwright test engineer performing automated test repair.
You will receive a failing Playwright TypeScript test file and its error output.
Your job is to produce a corrected version of the test file.

${UTILS_API}

## REPAIR RULES

### Language
- Output must remain TypeScript. Never downgrade to JavaScript.
- Preserve all existing TypeScript types and annotations.

### Analysis
- Read the error carefully: identify the root cause (selector mismatch, timing, assertion, import, URL)
- Only change what is necessary to fix the failure
- Preserve the test intent and structure

### URL Fixes
- If you see any hardcoded URL (http://localhost:3000, staging URL, etc.), replace with a relative route.
  page.goto("http://localhost:3000/fr") → page.goto("/fr")
  request.get("http://localhost:3000/robots.txt") → request.get("/robots.txt")

### Import Fixes
- If the test imports from "@playwright/test", replace with "../utils/consoleGuard.js"
- If cookie logic is inlined, replace with helpers from "../utils/cookies.js"
- If navigation+overlay is inlined, replace with navigateTo() from "../utils/navigation.js"

### Selector Fixes
- If a selector fails, try: getByRole(), getByLabel(), getByText() with the exact visible text
- NEVER switch to CSS class selectors or nth-child
- NEVER use arbitrary data-testid values — only those inferable from visible UI or the fixture

### Timing Fixes
- Replace page.waitForTimeout() or any arbitrary sleep with a locator assertion (e.g. expect(locator).toBeVisible({ timeout }))
- navigateTo() already handles waitForLoadState("load") — remove any redundant waitForLoadState calls after it (this includes inside helper functions defined in the same file)
- NEVER use waitForLoadState("networkidle") — Next.js HMR keeps connections open so it never resolves in dev mode; use "load" instead
- Replace Promise.race() + manual timeout fallbacks with a single locator assertion; let Playwright's auto-retry handle the wait
- If a test iterates over a dynamic list (nav links, menu items) in a single test, it will exceed the 30s timeout — replace with a for…of loop at describe level over a fixed small set
- If the test uses test.each(), replace with a for…of loop — test.each is not available on the consoleGuard extended test object and throws "TypeError: test.each is not a function" at runtime

### Assertion Fixes
- Replace any locator.isVisible()/isEnabled()/isChecked() + expect(bool).toBeTruthy/Falsy pattern with the equivalent web-first assertion (expect(locator).toBeVisible(), .toBeEnabled(), .toBeChecked())
- If a value assertion fails due to formatting, adjust the expected value to match reality
- If an element is conditionally rendered, guard the assertion with a visibility check

### Output Format
- Output ONLY the corrected TypeScript test code
- No explanations, no markdown, no comments about what changed
- The file must be a complete, runnable .spec.ts Playwright spec
`.trim()

// ─── PROMPT BUILDERS ──────────────────────────────────────────────────────────

export function buildGenerationPrompt(context: string): string {
  return `
Generate a Playwright TypeScript test file (.spec.ts) for the following context:

${context}

Decision rules:
- Route ends with .txt, .xml, .ico or starts with /api/ → HTTP test (request context). Do NOT use navigateTo or handleOverlays.
- Otherwise → UI test. Use navigateTo(page, route) for all navigation — it handles goto + networkidle + overlays.
- Cookie interactions → always use acceptCookies(page) / refuseCookies(page) from utils/cookies.js
- Pagination → use testPagination(page, config) from utils/pagination-tester.js
- NEVER hardcode any URL. Use relative routes only.
- Import { test, expect } ONLY from "../utils/consoleGuard.js"
- Output valid TypeScript only, no markdown.
`.trim()
}

export const UTIL_SYSTEM_PROMPT = `
You are an expert TypeScript/Playwright engineer.
Generate a single TypeScript utility file based on the specification given.
Output ONLY raw TypeScript code — no markdown fences, no explanations.
Use TypeScript ESM imports with .js extensions on local imports.
`.trim()

const UTIL_SPECS_BASE: Record<string, string> = {
  "consoleGuard.ts": `
Generate tests/utils/consoleGuard.ts — a Playwright test extension that:
- Exports a factory function createConsoleGuard(allowedErrors: RegExp[] = []) that:
  - Calls baseTest.extend<{ failOnConsoleError: boolean; _consoleGuard: void }>()
  - Adds option: failOnConsoleError (boolean, [false, { option: true }])
  - Adds a _consoleGuard fixture (auto: true) that:
    - Captures allowedErrors via closure (NOT as a fixture option — see note below)
    - Listens to page "console" events (type === "error") and "pageerror" events
    - Ignores errors matching any pattern in the allowedErrors closure array
    - After the test, throws if failOnConsoleError is true and uncaught errors were collected
  - Returns the extended test object
- Exports:
  - const test = createConsoleGuard()  (default, no pattern filtering)
  - createConsoleGuard (named export, for specs that need pattern filtering)
  - expect (re-exported from "@playwright/test")
  - type Page (re-exported from "@playwright/test")
- ⚠️ IMPORTANT: Do NOT add allowedConsoleErrors as a Playwright option fixture.
  Playwright 1.55 silently unwraps any array passed via test.use() as a [value, options] tuple,
  keeping only the first element. Use a closure variable instead.
`.trim(),

  "cookies.ts": `
Generate tests/utils/cookies.ts — a Playwright cookie consent helper.
- Import { type Page } from "@playwright/test"
- Read "COOKIE COMPONENT CODE" in the project context to identify:
  - The exact data-testid of the cookie banner container
  - The exact data-testid of the accept button
  - The exact data-testid of the decline/refuse button
  - The cookie key name and JSON structure stored in document.cookie (look for js-cookie, localStorage, or document.cookie usage)
- acceptCookies(page: Page): Promise<void> — waits for accept button to be visible (8000ms), clicks it, then waits for the consent cookie to appear in document.cookie. Silently ignores if banner not found.
- refuseCookies(page: Page): Promise<void> — same for decline button.
- getCookieContext(page: Page): Promise<Record<string, boolean> | null> — reads document.cookie, finds the consent cookie key, JSON.parse + decodeURIComponent, returns null if not found.
- Export: acceptCookies, refuseCookies, getCookieContext
`.trim(),

  "navigation.ts": `
Generate tests/utils/navigation.ts — a Playwright navigation helper:
- Import { type Page } from "@playwright/test"
- Import { getBaseUrl } from "./constants.js"
- navigateTo(page: Page, route: string): Promise<void> — await page.goto(getBaseUrl() + route, { waitUntil: "domcontentloaded" }), then waitForLoadState("load")
  NOTE: do NOT use waitForLoadState("networkidle") — Next.js HMR keeps the connection open and networkidle is never reached in dev mode.
- goToNextPage(page: Page, testId?: string): Promise<void> — scroll to and click getByTestId(testId ?? "next-page"), then waitForLoadState("load")
- goToPreviousPage(page: Page, testId?: string): Promise<void> — scroll to and click getByTestId(testId ?? "prev-page"), then waitForLoadState("load")
`.trim(),

  "constants.ts": `
Generate tests/utils/constants.ts — a simple URL constant helper:
- Read "BASE URL ENV VARS TO CHECK" from the project context to determine the right env var(s).
- getBaseUrl(): string — returns the first truthy value from the project's base URL env vars, falling back to "http://127.0.0.1:3000".
`.trim(),

  "filter-tester.ts": `
Generate tests/utils/filter-tester.ts — a Playwright filter interaction helper:
- Import { type Page } from "@playwright/test"

- Interface FilterTestConfig:
  { containerTestId?: string; filterItemTestId?: string; resultsContainerTestId?: string }

- detectFilters(page: Page): Promise<{ hasFilters: boolean; filterCount: number; filterTestIds: string[] }>
  Queries all visible [data-testid] attributes that match /filter|filtre|facet|refinement|sort|tri/i.
  Also counts visible filter inputs (select, input[type=checkbox], input[type=radio], [role=combobox])
  inside any element whose data-testid, aria-label, or class matches those patterns.
  Returns hasFilters: true if at least one testid OR one filter input is found.

- testFilters(page: Page, config: FilterTestConfig): Promise<void>
  Orchestrates a full filter test:
  1. Call detectFilters(page) — if hasFilters is false, return immediately (caller's beforeAll guard already handles skip).
  2. Locate the filter container via config.containerTestId if provided, otherwise via [data-testid*="filter" i].
  3. Find the first interactive filter element (checkbox, radio, select, [role=option]) inside the container.
  4. If config.resultsContainerTestId is provided, record the initial text of the results container.
  5. Interact with the filter element (check checkbox / select first option / click first radio).
  6. Wait for results to update: if resultsContainerTestId provided use waitFor({ state: "visible" }), else waitForLoadState("load").
  7. Assert results changed (text or count differs from recorded initial state if resultsContainerTestId was provided).
  8. Clear the filter: look for a button matching /clear|reset|réinitialiser/i or [data-testid*="reset"], [data-testid*="clear"].
     If no clear button is found, deselect the same element (uncheck checkbox / reset select / click radio again).
  9. Wait for results to restore.
  10. Assert results are restored (back to initial state if recorded, or results container is still visible).

- Export: testFilters, detectFilters, type FilterTestConfig
`.trim(),
}

// Keys exported so generateTests.ts can enumerate required utils
export const UTIL_SPECS_KEYS = Object.keys(UTIL_SPECS_BASE)

export function buildUtilPrompt(fileName: string, projectContext: string): string {
	const base =
		UTIL_SPECS_BASE[fileName] ?? `Generate the TypeScript utility file: ${fileName}`
	return `${base}\n\nPROJECT CONTEXT:\n${projectContext}`
}

// ─── FIXTURE GENERATION PROMPT ───────────────────────────────────────────────

export const FIXTURE_SYSTEM_PROMPT = `
You are an expert Playwright test engineer for Next.js applications.
Your job is to analyze a React component or page file and generate a Playwright test fixture JSON.

## OUTPUT FORMAT
Output ONLY a valid JSON object — no markdown fences, no explanation, no comments.

The JSON must follow this exact schema:
{
  "name": "<kebab-case unique name derived from file path>",
  "route": "<relative route to test, e.g. /en or /fr/contact>",
  "description": "<one-line description of what is being tested>",
  "priority": "high" | "medium" | "low",
  "locale": "<locale if applicable, e.g. en, fr — omit if not localized>",
  "features": ["<feature1>", "<feature2>"],
  "testCases": [
    {
      "name": "<descriptive test name>",
      "steps": ["<step 1>", "<step 2>"],
      "assertions": ["<assertion 1>"]
    }
  ]
}

## RULES
- Generate 2-4 meaningful test cases based on what the component visibly does
- Infer the route from the file path: pages/contact/index.jsx → /contact, pages/[locale]/about.jsx → /en/about
- For components (not pages), set route to the most likely parent page route
- Priority: "high" for page-level or critical UI, "medium" for feature components, "low" for minor UI
- Feature names must be kebab-case strings
- Test cases must be independent and cover distinct visible behaviors
- Never test implementation details — test visible, user-facing behavior
- Focus on: element visibility, navigation, user interaction, data display
- If the component has localized routes (e.g. /[locale]/), generate separate test cases for /en and /fr
`.trim()

export function buildFixtureFromComponentPrompt(
  filePath: string,
  fileContent: string,
  availableRoutes: string[]
): string {
  return `
Analyze this component/page file and generate a test fixture JSON.

FILE PATH: ${filePath}

FILE CONTENT:
${fileContent.slice(0, 4000)}

AVAILABLE ROUTES IN PROJECT:
${availableRoutes.slice(0, 40).join("\n")}

Output ONLY the JSON fixture. No explanation, no markdown fences.
`.trim()
}

export function buildFixPrompt(testCode: string, errorLog: string, context: string): string {
  return `
Fix the following failing Playwright TypeScript test.

## ORIGINAL TEST CODE:
\`\`\`typescript
${testCode}
\`\`\`

## ERROR LOG:
\`\`\`
${errorLog}
\`\`\`

## TEST CONTEXT:
${context}

Output only the corrected TypeScript test code. No explanations.
`.trim()
}
